TMS.NET06.Parfume.Manager.MVC/Areas/Admin/Controllers/BrandsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TMS.NET06.Parfume.Manager.MVC.Data;
using TMS.NET06.Parfume.Manager.MVC.Data.Models;

namespace TMS.NET06.Parfume.Manager.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BrandsController : Controller
    {
        private readonly ParfumeShopContext _context;
        private readonly IWebHostEnvironment _env;

        public BrandsController(ParfumeShopContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        // GET: Brands
        public async Task<IActionResult> Index()
        {
            return View(await _context.Brands.ToListAsync());
        }

        // GET: Brands/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.BrandId == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // GET: Brands/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Brands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Brand brand, [Bind] IFormFile uploadLogo, [Bind] IFormFile uploadFrontImage)
        {
            string directoryPath = Path.Combine(_env.WebRootPath, "img", "brand-img");
            CopyFiles(directoryPath, uploadLogo);
            CopyFiles(directoryPath, uploadFrontImage);

            string imagePathRel = "~/img/brand-img";
            SaveImagesInModel(brand, imagePathRel, uploadLogo);
            SaveImagesInModel(brand, imagePathRel, uploadFrontImage, false);

            if (ModelState.IsValid)
            {
                _context.Add(brand);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(brand);
        }

        // GET: Brands/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands.FindAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        // POST: Brands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Brand brand, [Bind] IFormFile uploadLogo, [Bind] IFormFile uploadFrontImage) 
        {
            if (id != brand.BrandId)
            {
                return NotFound();
            }

            string directoryPath = Path.Combine(_env.WebRootPath, "img", "brand-img");
            CopyFiles(directoryPath, uploadLogo);
            CopyFiles(directoryPath, uploadFrontImage);

            string imagePathRel = "~/img/brand-img";
            SaveImagesInModel(brand, imagePathRel, uploadLogo);
            SaveImagesInModel(brand, imagePathRel, uploadFrontImage, false);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.BrandId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Brands/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.BrandId == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brand = await _context.Brands.FindAsync(id);
            _context.Brands.Remove(brand);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrandExists(int id)
        {
            return _context.Brands.Any(e => e.BrandId == id);
        }

        private async void CopyFiles(string directoryPath, IFormFile uploadImage)
        {
            DirectoryInfo dirInfo = new DirectoryInfo(directoryPath);
            if (!dirInfo.Exists)
            {
                dirInfo.Create();
            }

            if (uploadImage != null)
            {
                if (uploadImage.Length > 0)
                {
                    string filePath = Path.Combine(directoryPath, uploadImage.FileName);
                    using (Stream fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await uploadImage.CopyToAsync(fileStream);
                    }
                }
            }

        }

        private void SaveImagesInModel(Brand brand, string imagePathRel, IFormFile uploadImage, bool isLogo = true)
        {
            if (uploadImage != null)
            {
                if (uploadImage.Length > 0)
                {
                    if (isLogo)
                        brand.Logo = imagePathRel + "/" + uploadImage.FileName;
                    else
                        brand.FrontImage = imagePathRel + "/" + uploadImage.FileName;
                }
            }

        }
    }
}

TMS.NET06.Parfume.Manager.MVC/Areas/Admin/Views/Brands/Create.cshtml
@model TMS.NET06.Parfume.Manager.MVC.Data.Models.Brand

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Brand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Имя</label>
                <input type="text" asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">Pick logo</label>
                <input type="file" class="form-control-file" id="Logo" name="uploadLogo">
            </div>

            <div class="form-group">
                <label class="control-label">Pick front image</label>
                <input type="file" class="form-control-file" id="ImagesSmall" name="uploadFrontImage">
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script>
    function deleteInput(inputId, btnId) {

        var el = document.getElementById(inputId);
        var btn = document.getElementById(btnId);
        el.remove();
        btn.remove();

    }
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TMS.NET06.Parfume.Manager.MVC/Areas/Admin/Views/Brands/Delete.cshtml
@model TMS.NET06.Parfume.Manager.MVC.Data.Models.Brand

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Brand</h4>
    <hr />
    <dl>
        <dt>Имя</dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BrandId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TMS.NET06.Parfume.Manager.MVC/Areas/Admin/Views/Brands/Details.cshtml
@model TMS.NET06.Parfume.Manager.MVC.Data.Models.Brand

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Brand</h4>
    <hr />
    <dl class="row">
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BrandId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TMS.NET06.Parfume.Manager.MVC/Areas/Admin/Views/Brands/Edit.cshtml
@model TMS.NET06.Parfume.Manager.MVC.Data.Models.Brand

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Brand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BrandId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Name</label>
                <input type="text" asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Logo" class="control-label">Logo</label>
                <input id="Logo" type="text" asp-for="Logo" class="form-control" />
                @*<button onclick="deleteInputValue('Logo');">X</button>*@
            </div>
            <div class="form-group">
                <label asp-for="FrontImage" class="control-label">FrontImage</label>
                <input id="frontImage" type="text" asp-for="FrontImage" class="form-control" />
                @*<button onclick="deleteInputValue('frontImage');">X</button>*@
            </div>
            @*<div class="form-group">
            <label class="control-label"><b>product images</b></label>
            <input name="images" id="logo" value="@Model.Logo" class="form-control" />
            <button id="buttonDeleteLogo" onclick="deleteInput('logo', 'buttonDeleteLogo');">Удалить</button>
        </div>
        <div class="form-group">
            <label class="control-label"><b>product images</b></label>
            <input name="images" id="frontImage" value="@Model.FrontImage" class="form-control" />
            <button id="buttonDeleteFrontImage" onclick="deleteInput('frontImage', 'buttonDeleteFrontImage');">Удалить</button>
        </div>*@
            <div class="form-group">
                <label class="control-label">Pick logo</label>
                <input type="file" class="form-control-file" id="Logo" name="uploadLogo">
            </div>

            <div class="form-group">
                <label class="control-label">Pick front image</label>
                <input type="file" class="form-control-file" id="ImagesSmall" name="uploadFrontImage">
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*<script>
    function deleteInputValue(inputId) {

        var el = document.getElementById(inputId);
        el.value = "";
       }
</script>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TMS.NET06.Parfume.Manager.MVC/Areas/Admin/Views/Brands/Index.cshtml
@model IEnumerable<TMS.NET06.Parfume.Manager.MVC.Data.Models.Brand>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-area="Admin" asp-controller="Brands" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr><td>@item.BrandId</td> 
            <td>@item.Name</td>
            <td>
                <a asp-area="Admin" asp-action="Edit" asp-route-id="@item.BrandId">Edit</a>
                <a asp-area="Admin" asp-action="Details" asp-route-id="@item.BrandId">Details</a>
                <a asp-area="Admin" asp-action="Delete" asp-route-id="@item.BrandId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>